### ISSUE TITLE
Unable to Sign In

### ISSUE THREAD

**Issue by deeps-vantiva** [sergio11/fitflextv_android#1]
Open Sign In Page, the email and password field will be already prefilled
email - ssanchez@yopmail.com
password - some prefilled password

Submit Button(Start Sweating) Click -> An error occurred, please try again.

Also, I was unable to build the project as `github.properties` was missing. So, I created one and added my credentials into it.
After that I received another error that `google-services.json` is missing. So, I created a firebase project as well.

Does this project require some more additional setup on Firebase console in order to work(like creating DB, adding users etc.) ?

**Comment by sergio11** [comment]
Hi @deeps-vantiva , 

Thanks for your question! exactly, you must provide your own firebase configuration in order to setup the project, preparing your own firestore and firestorage, I couldn't share my configuration due to service limits

I am going to prepare a section in the README in order to explain that

Thanks
